### PR TITLE
Update zookeeper dependency on evalcast; cleanup various zookeeper things, animalia DESCRIPTION

### PR DESCRIPTION
**Pull request by dshemetov**
Since evalcast branches are getting merged and pruned, update the dependency on `evalcast-killcards` to `evalcast`.

While we're at it:
* fix some lint issues
* bump Roxygen version
* remove unused packages (MMWRweek, fs)
* add implicit dependencies (covidcast, rlang, tidyselect)

TODO:
- [x] try to fix tests (still broken) (@brookslogan I see you touched these last September, mind taking a look at `test-state-corrector.R` and finding what's going wrong? I'm having trouble parsing what the tests are doing.)

### CODE REVIEW

**Comment by brookslogan** [comment]
I'm currently:
- reverting CODEOWNERS change to reduce GitHub review "spam"
- fixing mangled, stochastic corrector test changes

then will look over the other changes.

**Comment by dshemetov** [comment]
Would be nice to merge #123 after, would clean up the last bits of tech debt in this repo (that branch is just Dan's modifications to the Reichlab formatter that we've been using without issue for 6+ months now, so should be safe).

**Comment by dshemetov** [comment]
@brookslogan thank you for fixing the tests, deterministic tests and non-API data is a good call 👍. Anything else we need to do here?

**Comment by brookslogan** [comment]
I still need to review the other changes you made (and you should review mine).

**Comment by brookslogan** [comment]
Looks good now.  There does seem to be some mixing of `@importFrom` and `::`, although I guess some people use a mix based on whether other developers are expected to know about a particular function or not.  Doesn't seem like something to worry about in this case.  I suppose in other cases, being unclear about a convention might lead to mistakenly omitting both and getting a `base` member with an identical name instead, but we should probably realize it.  Maybe the main cost instead is purely personal ideas of aesthetics and wasting time discussing them (oops!).  Going ahead and merging.

**Comment by dshemetov** [comment]
I often have strong aesthetic views on code these days, but I must confess, with regard to `@importFrom` and `::`, I feel like I am strongly inclined to one on Monday and then strongly inclined to the other on Friday, without really noticing I've made an allegiance switch 🤷.

**Pull request merged**
