### PR TITLE
update corrections rmds to run in pipeline

### PR DESCRIPTION
**Pull request by dajmcdon**
@bnaras 

This PR adds the RMDs to produce the corrections checks. The RMDs source the `production_params.R` script. 

Can you review and make sure that they run in production?

The knitted htmls should probably go in a separate directory (say `forecasts/correction-checks`) and can be safely overwritten each day (no need to keep all versions around).

### CODE REVIEW

**Review by bnaras — COMMENTED** [review]
Looks good to me.  I'm unable to log in to the prod server from where I am to fully check, but the corrections seems fine to me.

**Review by bnaras — APPROVED** [review]

**Review by bnaras — COMMENTED** [review]
One question though: why is `start_day` for `anteater` and `zebra` going all the way back to 2020-06-01?

**Comment by dajmcdon** [comment]
It turns out, we sometimes want to backdistribute corrections over 5 or 6 months. If there isn't data that far back, then they'll only get backdistributed over whatever is available. So easiest is just to grab a lot of data. The forecaster doesn't use most of it.

**Comment by bnaras** [comment]
I'll go ahead and merge.

**Pull request merged**
